### ISSUE TITLE
Pre-train models available?

### ISSUE THREAD

**Issue by RayShing** [buaavrcg/BakedAvatar#1]
Hello, thank you for your awesome work! May I ask whether you could release the pre-trained models? Thanks!

**Comment by dhbloo** [comment]
Hi, We will release the pre-trained model soon :)

**Comment by jessehao123** [comment]
> Hi, We will release the pre-trained model soon :)

Thanks. We're waiting for it.

**Comment by dhbloo** [comment]
Hi all, we now provide an example of pre-trained checkpoint [here](https://drive.google.com/file/d/137TTr8GENZmPZ-Me1SatymMCiVDKqDPR/view?usp=drive_link).

**Comment by zhiyoujingtian** [comment]
Sample cannot be downloaded
![image](https://github.com/user-attachments/assets/342a4182-15d5-4666-a287-fa521c8533ff)

**Comment by dhbloo** [comment]
Should have been fixed now.
