### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by annakrasotkina** [buaavrcg/BakedAvatar#10]
Hi! 
Thank you so much for the interesting project! BakedAvatar looks very impressive.
I'm trying to get it working on a lab computer. Where should I put the preprocessed dataset from subject1 and subject2?
Cheers,
Anna

**Comment by dhbloo** [comment]
Hi,

You can download the two example datasets for [subject_1, subject_2](https://drive.google.com/drive/folders/1w5_RiCBQ-bZmFzcWdml7ReWZTO2I7V2y). Then, unzip them and place them in the `data/datasets` directory relative to the root of this project.

We have added more detailed instructions in the README.
