### ISSUE TITLE
See  only black window in a browser when launch serve

### ISSUE THREAD

**Issue by crankyz** [buaavrcg/BakedAvatar#11]
But some errors there:
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 304 in 17 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /jsUtils/materialize.min.css
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /jsUtils/jquery-3.6.4.min.js
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /jsUtils/materialize.min.js
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /jsUtils/webgl-lessons-ui.js
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /jsUtils/webgl-utils.js
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /dist/main.js
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 304 in 10 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 304 in 7 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 304 in 6 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 304 in 10 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 304 in 10 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 304 in 8 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /fonts/roboto/Roboto-Regular.woff2
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 404 in 3 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /fonts/roboto/Roboto-Regular.woff
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 404 in 2 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /fonts/roboto/Roboto-Regular.ttf
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 404 in 2 ms
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 GET /mesh_data/metadata.json
 HTTP  2/25/2024 4:42:34 PM 127.0.0.1 Returned 404 in 1 ms

**Comment by crankyz** [comment]
Problem solved when I moved finetune and output folder to web_demo.

**Comment by alasokolova** [comment]
Hi @crankyz 
Could you please explain which folders and files should be located in web_demo directory?
I moved finetune_mesh_output  and sequence_data there, but still getting the black window (although with "common loaded MLP loaded" logs in the bottom)

**Comment by alasokolova** [comment]
@dhbloo could you please describe what should be the structure inside web_demo folder so that web demo works?
 Thanks!
