### ISSUE TITLE
Web demo shows only black window.

### ISSUE THREAD

**Issue by Abdelrahman350** [buaavrcg/BakedAvatar#14]
Hello, I am really interested in your work. The issue is I only get black window when typing `serve` in the terminal under the `web_demo` environment. Also the cross identity steps is really vague and not clear. If you can explain it more that would be very helpful. Thanks you so much for your good work.

**Comment by dhbloo** [comment]
Hi, have you correctly placed `mesh_data` and `sequence_data` onto the web_demo directory? If you encounter other errors in the webpage, you can press F12 and take a screenshot of any messages that appear.

For cross identity reenactment in the web demo, you can simply use another person's sequence to run the reenactment.

**Comment by Abdelrahman350** [comment]
> Hi, have you correctly placed `mesh_data` and `sequence_data` onto the web_demo directory? If you encounter other errors in the webpage, you can press F12 and take a screenshot of any messages that appear.
> 
> For cross identity reenactment in the web demo, you can simply use another person's sequence to run the reenactment.

Thank you for your response, yes I followed those steps and got a black window. Please, consider writing a more detailed readme file explaining how to do cross identity reenactment in general.

**Comment by dhbloo** [comment]
I'm sorry that the instructions were not clear enough. We have updated some instructions in the readme.

If you have followed the steps and are still seeing a black window, please try pressing F12 to get the dev console out in the web browser, and check if some related error messages are printed in the console, so it would be clear for us to find which step might be wrong that caused the error.
