### ISSUE TITLE
flame_params.json not found

### ISSUE THREAD

**Issue by zhangjuexin** [buaavrcg/BakedAvatar#15]
Hi, I am stuck at the "Export assets and run the real-time web demo" step becasue I did not find the flame_params.json in any folder. As described in the comments, the flame_params.json file should be in train and test subfolders. However, I can only find one .json file named "metadata" in /data/expriments/subject1/finetune_mesh_data/iter_30000/mesh_data/metadata.json. Hence, could you please provide the path of flame_params.json file? Or am I missing something during running the scripts? My files in /data/expriments/subject1/ are as follows:
<img width="310" alt="image" src="https://github.com/buaavrcg/BakedAvatar/assets/39945522/6274d006-fe98-4fc3-a039-75bb6ced500a">

**Comment by dhbloo** [comment]
Hi, the `flame_params.json` file is in the _video dataset folder_. Each video in one sub-directory should have one `flame_params.json` file. You can specify multiple json files when exporting the sequences for the web demo.
