### ISSUE TITLE
update dataset download link

### ISSUE THREAD

**Issue by zhengyuf** [buaavrcg/BakedAvatar#17]
Hello, 

We're no longer hosting our dataset on google drive. I got many share requests for the old google folder, but I'm not allowed to grant access. Please download the data following the links here: https://github.com/zhengyuf/PointAvatar

To the authors: Congrats on the nice work. It'd be great if you could update the link when convenient, thank you :)

best,
Yufeng

**Comment by dhbloo** [comment]
Hi,

Thanks for your update! We have now fixed the dataset link in readme.
