### ISSUE TITLE
reenactment speed

### ISSUE THREAD

**Issue by NikoBele1** [buaavrcg/BakedAvatar#18]
Hi,

the provided demo reenactment on subject 1 and 2 is estimated to take very long on my 4090 machine ~10hours. Is this normal ?

Best regards

**Comment by dhbloo** [comment]
Hi, 

I think that is not normal. Which script did you run, and with what arguments?

**Comment by dhbloo** [comment]
It seems this was caused by a slight mistake in the reenactment command, which has been brought up to me by someone recently. 
The readme has been fixed.
