### ISSUE TITLE
where is export_flame_params.py?

### ISSUE THREAD

**Issue by RayShing** [buaavrcg/BakedAvatar#3]
Hello, I have finished training and evaluation based on README. Now I am going to run the real-time demo. However, I am a bit confused about how to run this part: 

```
# export the FLAME parameter sequence for reenactment
python scripts/export_flame_params.py <path to 1st flame_params.json> <path to 2nd flame_params.json> ... --output ./sequence_data
```

There is not `export_flame_params.py`, only `export_flame_sequence`. Also, what is <path to 1st flame_params.json> <path to 2nd flame_params.json>?

**Comment by endlesswho** [comment]
> Hello, I have finished training and evaluation based on README. Now I am going to run the real-time demo. However, I am a bit confused about how to run this part:
> 
> ```
> # export the FLAME parameter sequence for reenactment
> python scripts/export_flame_params.py <path to 1st flame_params.json> <path to 2nd flame_params.json> ... --output ./sequence_data
> ```
> 
> There is not `export_flame_params.py`, only `export_flame_sequence`. Also, what is <path to 1st flame_params.json> <path to 2nd flame_params.json>?

I guess it's the flame_params from train and test datasets.
I successly generate the  sequence_data, but the web demo won't work. 
![image](https://github.com/buaavrcg/BakedAvatar/assets/8555404/82004c5c-22b9-4b57-8411-d46f905aa4ab)

**Comment by dhbloo** [comment]
Hi, we made a typo in the readme, it should be `export_flame_sequence.py`. The `flame_params.json` are the ones in the train and test subfolders.

@endlesswho Could you open the console (press F12) and copy the error messages here? Thanks very much.

**Comment by jerrymatjila** [comment]
There is a bug. Remove `ss` in line
 https://github.com/buaavrcg/BakedAvatar/blob/af57b4a43abb4f3ce7197878c3b0c38632459f43/web_demo/src/shaders.js#L84

Then do build
```bash
npm run build
```

**Comment by dhbloo** [comment]
> There is a bug. Remove `ss` in line
> 
> https://github.com/buaavrcg/BakedAvatar/blob/af57b4a43abb4f3ce7197878c3b0c38632459f43/web_demo/src/shaders.js#L84
> 
> Then do build
> 
> ```shell
> npm run build
> ```

Thanks for pointing out! It might be accidentally introduced when cleaning up the code.
