### ISSUE TITLE
Preprocessed data links no longer work

### ISSUE THREAD

**Issue by jonas-helios** [buaavrcg/BakedAvatar#6]
The preprocessed dataset links for subject 1 (https://dataset.ait.ethz.ch/downloads/IMavatar_data/data/yufeng.zip) and subject 2 (https://dataset.ait.ethz.ch/downloads/IMavatar_data/data/soubhik.zip) are not working. Could you please check/fix? Thanks!

**Comment by jingli-wtbox** [comment]
find them from below link:

[subject_1, subject_2](https://drive.google.com/drive/folders/1w5_RiCBQ-bZmFzcWdml7ReWZTO2I7V2y
)

**Comment by alasokolova** [comment]
Hey, for these links the access is required, could you please provide it?
