### ISSUE TITLE
Cross identity

### ISSUE THREAD

**Issue by balogistvan** [buaavrcg/BakedAvatar#7]
Hello. Thank you for this great work. Can you tell me how to turn on the cross identitiy reenactment?

**Comment by dhbloo** [comment]
Hi, for cross-identity reenactment in the web demo, when you export the flame sequence, please also include other flame sequences you want to use as the driving source. Then, in the web demo, choose the correct source to see the reenactment results.

**Comment by balogistvan** [comment]
Thank you.

**Comment by balogistvan** [comment]
Thank you.
