### ISSUE TITLE
Error on stage 2

### ISSUE THREAD

**Issue by huangxin168** [buaavrcg/BakedAvatar#9]
Great jobs! Thank you again for your sharing.

I'm using conda env. after stage1 training, I do stage 2 with command:
accelerate launch scripts/runner.py -c config/subject1.yaml -t mesh_export
but got the following errors, it seems pymeshlab can not run under conda environment.
how can I solve this problem?

(bakedavatar) root@192-168-2-26:/BakedAvatar/code# accelerate launch scripts/runner.py -c config/subject1.yaml -t mesh_export
Command Line Args:   -c config/subject1.yaml -t mesh_export
Config File (config/subject1.yaml):
rundir:            ../data/experiments
run_name:          subject1
dataset_class:     dataset.real.RealVideoDataset
data_dir:          ../data/datasets/yufeng
train_subdirs:     ['MVI_1810', 'MVI_1811', 'MVI_1814']
val_subdirs:       ['MVI_1812']
val_subsample:     list([0, 200, 500, 800, 1000])
test_subdirs:      ['MVI_1812']
test_subsample:    10
img_res:           [256, 256]
model_class:       model.dmmavatar.DMMavatar
model_args:        {'dim_expression': 50, 'dim_frame_latent': 0, 'dim_radiance_feature': 3, 'dim_pos_feature': 8, 'num_texture_basis': 16, 'ghostbone': True, 'manifold_network_class': 'model.manifold_network.ManifoldNetwork', 'manifold_network_args': {'pe_freqs': 5, 'num_layers': 6, 'dim_hidden': 256, 'init_radius': 0.5}, 'deformer_network_args': {'pe_freqs': 0, 'num_layers': 3, 'dim_hidden': 128}, 'radiance_network_class': 'model.radiance_network.RadianceNetwork', 'radiance_network_args': {'pe_freqs': 12, 'num_layers': 6, 'num_base_layers': 4, 'dim_hidden': 512, 'skip_input_layers': [4], 'texture_basis_args': {'dim_global_hidden': 64, 'num_global_layers': 3, 'dim_spatial_hidden': 16, 'num_spatial_layers': 2, 'temperature': 10.0}}, 'radiance_decoder_class': '', 'radiance_decoder_args': {'dir_embedding_freqs': 0, 'num_layers': 2, 'dim_hidden': 16}, 'manifold_renderer_args': {'num_manifold_levels': 8, 'manifold_level_start': -0.2, 'manifold_level_end': 0.0, 'manifold_samples': 48, 'manifold_secant_steps': 6, 'bounding_sphere_radius': 1.1, 'use_gt_mask_when_training': False, 'use_presort': False}}
batch_size:        6
num_rays:          2048
num_workers:       4
no_shuffle:        False
loss_class:        model.loss.Loss
loss_args:         {'rgb_loss_weight': 1.0, 'mask_loss_weight': 10.0, 'mask_alpha': 50.0, 'mask_target_gamma': 10.0, 'flame_loss_weight': 1.0, 'flame_distance_loss_weight': 1.0, 'flame_dist_threshold': 0.002, 'flame_target_gamma': 0.0, 'flame_loss_decay_iterations': 20000, 'use_semantic': True}
optimize_latent:   False
optimize_expression:True
optimize_pose:     True
optimize_camera:   True
scheduler_class:   torch.optim.lr_scheduler.MultiStepLR
scheduler_args:    {'milestones': [10000, 20000, 25000], 'gamma': 0.5}
iterations:        30000
lr:                0.0003
lr_input:          5e-05
clip_grad_norm:    1.0
Defaults:
--seed:            42
--train_subsample: 1
--dataset_args:    {}
--vis_args:        {}
--export_type:     marching_cube
--flame_num_subdivision:0
--flame_sample_points:200000
--flame_fitting_loss_class:model.loss.MeshFittingLoss
--flame_fitting_loss_args:{}
--mc_res_init:     16
--mc_res_up:       5
--mc_query_scale:  1.2
--mc_center_offset_x:0.0
--mc_center_offset_y:0.1
--mc_center_offset_z:0.0
--mesh_angle_limit:120
--mesh_high_angle_face_percentage:0.15
--mesh_high_angle_expand_iterations:3
--mesh_target_face_count:10000
--mesh_remesh_iteration:0
--mesh_remesh_target_len_percentage:1
--optim_class:     torch.optim.AdamW
--optim_args:      {}
--fitting_iterations:10000
--fitting_lr:      0.001
--show_it:         10
--save_it:         1000
Wrote config file to ../data/experiments/subject1/run_config.yaml
------------------------------------------------------------
Loaded 4231 testing frames from ../data/datasets/yufeng/['MVI_1810', 'MVI_1811', 'MVI_1814'].
creating the FLAME Decoder, n_shape: 100, n_exp: 50
/root/anaconda3/envs/bakedavatar/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loaded checkpoint (iter 30000, samples 180000) from: ../data/experiments/subject1/checkpoints/iter_30000
Start exporting mesh (type: marching_cube)...
Marching cube final resolution: 512
Marching cube mesh 0: level=-0.20000000298023224
Initial mesh vertices: 673070, faces: 1344532
Cleaned vertices: 609461, faces: 1217926
Traceback (most recent call last):
  File "/BakedAvatar/code/scripts/runner.py", line 315, in <module>
    mesh_export(**args)
  File "/BakedAvatar/code/scripts/mesh_export.py", line 745, in mesh_export
    marching_cube(
  File "/BakedAvatar/code/scripts/mesh_export.py", line 592, in marching_cube
    vertices, faces = apply_mesh_simplification(vertices, faces, **mesh_kwargs)
  File "/BakedAvatar/code/scripts/mesh_export.py", line 312, in apply_mesh_simplification
    vertices, faces = decimate_mesh(vertices, faces, mesh_target_face_count)
  File "/BakedAvatar/code/scripts/mesh_export.py", line 197, in decimate_mesh
    import pymeshlab
  File "/root/anaconda3/envs/sadtalker2/lib/python3.10/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /root/anaconda3/envs/sadtalker2/lib/python3.10/site-packages/pymeshlab/lib/libQt5Xml.so.5: undefined symbol: _ZdlPvm, version Qt_5
Traceback (most recent call last):
  File "/root/anaconda3/envs/bakedavatar/bin/accelerate", line 10, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/bakedavatar/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/anaconda3/envs/bakedavatar/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/root/anaconda3/envs/bakedavatar/lib/python3.10/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/bakedavatar/bin/python3.10', 'scripts/runner.py', '-c', 'config/subject1.yaml', '-t', 'mesh_export']' returned non-zero exit status 1.

**Comment by dhbloo** [comment]
Hi, it seems the installed Pymeshlab has some issues with Qt. We haven't met such problems yet. Maybe you can try to reinstall a fresh conda environment?
